[package]
name = "sygma_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
moka = { version = "0.12", features = ["sync"] } # Cache TinyLFU
lazy_static = "1.4" # Inicialização de variáveis globais

